# Generated by Django 5.2.17 on 2026-08-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadrequest',
            name='baby_stage',
            field=models.CharField(blank=True, default='Expecting (Pregnant)', max_length=120),
        ),
        migrations.AlterField(
            model_name='leadrequest',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
