# Generated by Django 5.2.17 on 2026-08-12 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0002_leadrequest_baby_stage_alter_leadrequest_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadrequest',
            name='training_course_signup',
            field=models.BooleanField(default=True),
        ),
    ]
