# Generated by Django 5.2.17 on 2026-08-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0003_leadrequest_training_course_signup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadrequest',
            name='training_course_signup',
            field=models.CharField(default='Yes', max_length=10),
        ),
    ]
